/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myutil;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 *
 * @author nbp184
 */
public class ImagePanel extends javax.swing.JPanel {
    
    private BufferedImage image;

    /**
     * Creates new form ImagePanel
     * @param image
     */
    public ImagePanel(BufferedImage image) {
        initComponents();
        this.image = image;
        this.setSize(new Dimension(image.getWidth(), image.getHeight()));
        this.setPreferredSize(new Dimension(image.getWidth(), image.getHeight()));
    }
    
    public void setImage(BufferedImage image) {
        this.image = image;
        this.setSize(new Dimension(image.getWidth(), image.getHeight()));
        this.setPreferredSize(new Dimension(image.getWidth(), image.getHeight()));
        this.repaint();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        g.drawImage(image, 0, 0, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void fit() {
        Dimension d = new Dimension(image.getWidth(), image.getHeight());
        this.setSize(d);
        this.setPreferredSize(d);
        this.repaint();
    }
}
