/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myutil;

import java.awt.BorderLayout;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;

/**
 *
 * @author nbp184
 */
public class ImageDialog extends javax.swing.JDialog {

    private final ImagePanel ip;
    
    /**
     * Creates new form ImageDialog
     * @param parent
     * @param modal
     * @param image
     */
    public ImageDialog(java.awt.Frame parent, boolean modal, BufferedImage image) {
        super(parent, modal);
        initComponents();
        this.setLayout(new BorderLayout());
        ip = new ImagePanel(image);
        this.add(ip, BorderLayout.CENTER);
    }
    
    public void setImage(BufferedImage image) {
        ip.setImage(image);
        fit();
    }
    
    public void addIPMouseListener(MouseListener ml) {
        ip.addMouseListener(ml);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void fit() {
        ip.fit();
        this.setSize(new java.awt.Dimension(ip.getWidth() + 15, ip.getHeight() + 35));
    }
}
