/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myutil;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author nbp184
 */
public class VerticalTab extends javax.swing.JPanel {

    private final ArrayList<Tab> tabs;
    private int width;
    private int vgap;
    
    /**
     * Creates new form VerticalTab
     */
    public VerticalTab() {
        initComponents();
        FlowLayout l = new FlowLayout();
        vgap = l.getVgap();
        setLayout(l);
        tabs = new ArrayList<>();
        width = 0;
    }
    
    public void add(Component c, String name, boolean open) {
        Tab t = new Tab(this, c, name, open);
        add(t.btn);
        if(open) {
            add(c);
        }
        tabs.add(t);
    }
    
    public void fit() {
        width = 0;
        int height = 0;
        for(Tab tab : tabs) {
            if(tab.c.getWidth() > width) {
                width = tab.c.getWidth();
            }
            height += tab.btn.getHeight() + tab.c.getHeight() +2*vgap;
        }
        Dimension d;
        for(Tab tab : tabs) {
            d = tab.btn.getSize();
            d.width = width;
            tab.btn.setSize(d);
            tab.btn.setPreferredSize(d);
        }
        d = new Dimension();
        d.width = width;
        d.height = height;
        System.out.println(d);
        setSize(d);
        setPreferredSize(d);
    }
    
    void tabButtonClick(Tab t) {
        if(!t.open) {
            remove(t.c);
        } else {
            int index = 0;
            for(Component c : getComponents()) {
                if(t.btn.equals(c)) {
                    break;
                }
                index++;
            }
            add(t.c, index+1);
        }
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setOpen(int index, boolean open) {
        tabs.get(index).setOpen(open);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private static class Tab {
        
        private static int nextID = 0;
        
        Component c;
        JButton btn;
        String name;
        boolean open;
        final int id;
        final VerticalTab parent;
        
        public Tab(VerticalTab parent, Component c, String name, boolean open) {
            this.parent = parent;
            this.c = c;
            this.name = name;
            this.open = open;
            id = nextID++;
            if(open) {
                btn = new JButton("^ " +name);
            } else {
                btn = new JButton("v " +name);
            }
            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    buttonClick();
                }
            });
        }
        
        public void setOpen(boolean open) {
            if(this.open != open) {
                this.open = open;
                if(open) {
                btn.setText("^ " +name);
                } else {
                    btn.setText("v " +name);
                }
                parent.tabButtonClick(this);
            }
        }
        
        private void buttonClick() {
            open = !open;
            if(open) {
                btn.setText("^ " +name);
            } else {
                btn.setText("v " +name);
            }
            parent.tabButtonClick(this);
        }
        
    }

}
